export const definitions = {
  customers: {
    title: "Customers",
    singular: "customer",
    eyebrow: "CUSTOMER OPERATIONS",
    description: "One record for every relationship, across every product.",
    permission: "operate",
    defaults: {
      name: "",
      company: "",
      email: "",
      phone: "",
      status: "lead",
      notes: "",
      storeWorkspaceId: "",
    },
    statuses: ["lead", "active", "paused", "archived"],
    columns: [
      ["name", "Customer"],
      ["company", "Company"],
      ["email", "Contact"],
      ["status", "Status"],
      ["updatedAt", "Updated"],
    ],
  },
  products: {
    title: "Products",
    singular: "product",
    eyebrow: "PRODUCT PORTFOLIO",
    description: "Different delivery models. One consistent catalog.",
    permission: "catalog",
    defaults: {
      name: "",
      slug: "",
      description: "",
      category: "",
      model: "saas",
      requiredProviders: [],
      pricing: "subscription",
      status: "planned",
      website: "",
    },
    statuses: ["active", "planned", "retired"],
    columns: [
      ["name", "Product"],
      ["model", "Delivery model"],
      ["pricing", "Pricing"],
      ["status", "Status"],
      ["updatedAt", "Updated"],
    ],
  },
  installations: {
    title: "Installations",
    singular: "installation",
    eyebrow: "PRODUCT DELIVERY",
    description:
      "Track environments, releases and readiness from planning to handover.",
    permission: "operate",
    defaults: {
      name: "",
      customerId: "",
      productId: "",
      environment: "production",
      status: "planned",
      release: "",
      sourceUrl: "",
      endpoint: "",
      connectionIds: [],
      checks: [],
      evidence: "",
      notes: "",
    },
    statuses: ["planned", "ready", "live", "paused", "retired"],
    columns: [
      ["name", "Installation"],
      ["release", "Release"],
      ["environment", "Environment"],
      ["status", "Lifecycle"],
      ["updatedAt", "Updated"],
    ],
  },
  connections: {
    title: "Connections",
    singular: "connection",
    eyebrow: "INFRASTRUCTURE REGISTRY",
    description:
      "Customer account references and encrypted credentials, with clear ownership.",
    permission: "credentials",
    defaults: {
      name: "",
      customerId: "",
      provider: "vercel",
      ownership: "customer",
      accountId: "",
      resourceId: "",
      expiresAt: "",
      status: "recorded",
      notes: "",
    },
    statuses: ["recorded", "attention", "revoked"],
    columns: [
      ["name", "Connection"],
      ["provider", "Provider"],
      ["ownership", "Owned by"],
      ["hasCredential", "Credential"],
      ["status", "Status"],
    ],
  },
  tasks: {
    title: "Work queue",
    singular: "task",
    eyebrow: "DAILY OPERATIONS",
    description:
      "Follow-ups, renewals and handovers that keep your products moving.",
    permission: "operate",
    defaults: {
      title: "",
      customerId: "",
      installationId: "",
      assigneeId: "",
      status: "open",
      priority: "normal",
      dueAt: "",
      notes: "",
    },
    statuses: ["open", "in-progress", "done"],
    columns: [
      ["title", "Task"],
      ["priority", "Priority"],
      ["dueAt", "Due date"],
      ["status", "Status"],
      ["updatedAt", "Updated"],
    ],
  },
};
